spring:
  application:
    name: sentinel-core-example

  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      datasource:
        ds1:
          file:
            file: classpath:flowrule.json
            data-type: json
            rule-type: flow
        ds2:
          file:
            file: classpath:degraderule.json
            data-type: json
            rule-type: degrade
        ds3:
          file:
              file: classpath:authority.json
              data-type: json
              rule-type: authority
        ds4:
          file:
              file: classpath:system.json
              data-type: json
              rule-type: system
        ds5:
          file:
              file: classpath:param-flow.json
              data-type: json
              rule-type: param_flow
        ds6:
          nacos:
              server-addr: 127.0.0.1:8848
              username: nacos
              password: nacos
              data-id: flowrule.json
              data-type: json
              rule-type: flow

      block-page: /errorPage
      # filter:
      #   enabled: false
      # http-method-specify: false

server:
  port: 18083

management:
  endpoint:
    web:
        exposure:
            include: "*"
    health:
      show-details: always
      diskSpace:
        # we can disable health check, default is enable
        enabled: false
      # sentinel:
      #  enabled: false
