spring:
  application:
    name: service-consumer-reactive

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 18083

management:
  endpoints:
    web:
      exposure:
        include: '*'
