server:
  port: 18084

spring:
  application:
    name: sentinel-webflux-example

  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
      datasource:
        ds1:
          file:
            file: classpath:flowrule.json
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include=*:
