server:
  port: 80

spring:
  application:
    name: sentinel-circuit-breaker-example

  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        username: 'nacos'
        password: 'nacos'

  config:
    import: optional:nacos:sentinel-circuitbreaker-rules.yml
